-- 문답 QUESTION
INSERT INTO question (QUESTION, QUESTION_ID)
VALUES ("1. 상담시 친절하게 안내 받으시고 궁금한 사항에 대한 답변이 만족스러우셨습니까?", "QUESTION1");
INSERT INTO question (QUESTION, QUESTION_ID)
VALUES ("2. PT(1:1 퍼스널 트레이닝) 진행시 친절하게 안내 받으시고 궁금한 사항에 대한 답변이 만족스러우셨습니까?", "QUESTION2");
INSERT INTO question (QUESTION, QUESTION_ID)
VALUES ("3. OT(1:1 무료 PT) 진행시 친절하게 안내 받으시고 궁금한 사항에 대한 답변이 만족스러우셨습니까?", "QUESTION3");
INSERT INTO question (QUESTION, QUESTION_ID)
VALUES ("4. 헬스장 오픈, 마감시 시간을 정확히 준수하였습니까?", "QUESTION4");
INSERT INTO question (QUESTION, QUESTION_ID)
VALUES ("5. 전반적인 센터 이용이 만족스러우셨습니까?", "QUESTION5");

-- 답항 ANSWER
INSERT INTO answer (ANSWER, ANSWER_ID)
VALUES ("(1)매우만족", "ANSWER1");
INSERT INTO answer (ANSWER, ANSWER_ID)
VALUES ("(2)만족", "ANSWER2");
INSERT INTO answer (ANSWER, ANSWER_ID)
VALUES ("(3)보통", "ANSWER3");
INSERT INTO answer (ANSWER, ANSWER_ID)
VALUES ("(4)불만", "ANSWER4");
INSERT INTO answer (ANSWER, ANSWER_ID)
VALUES ("(5)매우불만", "ANSWER5");

-- 문항답항 QUESTION_ANSWER
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION1", "ANSWER1");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION1", "ANSWER2");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION1", "ANSWER3");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION1", "ANSWER4");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION1", "ANSWER5");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION2", "ANSWER1");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION2", "ANSWER2");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION2", "ANSWER3");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION2", "ANSWER4");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION2", "ANSWER5");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION3", "ANSWER1");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION3", "ANSWER2");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION3", "ANSWER3");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION3", "ANSWER4");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION3", "ANSWER5");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION4", "ANSWER1");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION4", "ANSWER2");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION4", "ANSWER3");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION4", "ANSWER4");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION4", "ANSWER5");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION5", "ANSWER1");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION5", "ANSWER2");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION5", "ANSWER3");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION5", "ANSWER4");
INSERT INTO question_answers (QUESTION_ID, ANSWER_ID)
VALUES ("QUESTION5", "ANSWER5");

select * from question;
select * from answer;
SELECT * FROM question_answers;
