-- survey
INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION1","ANSWER1","USER1");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION2","ANSWER2","USER1");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION3","ANSWER3","USER1");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION4","ANSWER4","USER1");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION5","ANSWER5","USER1");

-----------------------------------
INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION1","ANSWER1","USER2");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION2","ANSWER2","USER2");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION3","ANSWER3","USER2");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION4","ANSWER4","USER2");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION5","ANSWER5","USER2");
-----------------------------------
INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION1","ANSWER1","USER3");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION2","ANSWER2","USER3");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION3","ANSWER3","USER3");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION4","ANSWER4","USER3");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION5","ANSWER5","USER3");
-----------------------------------

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION1","ANSWER1","USER4");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION2","ANSWER2","USER4");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION3","ANSWER3","USER4");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION4","ANSWER4","USER4");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION5","ANSWER5","USER4");
-----------------------------------
INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION1","ANSWER1","USER5");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION2","ANSWER2","USER5");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION3","ANSWER3","USER5");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION4","ANSWER4","USER5");

INSERT INTO survey (QUESTION_ID,ANSWER_ID,USER_ID)
VALUES("QUESTION5","ANSWER5","USER5");
-----------------------------------